### ISSUE TITLE
Support media

### ISSUE THREAD

**Issue by gallarian** [Nouvelle-Techno-fr/JeBenevole.fr#14]
did you think about the support for the application?
currently after the discussion on the vocal,
we talked about:
- mobile
- PC desktop

do we need more and what will be the breakpoints?

**Comment by NouvelleTechno** [comment]
I'd say thé website should be responsive.
We discussed about PWA as well.

**Comment by kelkun89** [comment]
For the stopping point, I think that mobile, tablet and computer are enough, we will not go as far as television? even if we could !!!!

**Comment by NouvelleTechno** [comment]
Would go 4k as well

**Comment by kelkun89** [comment]
I never did that, so why not. I am open to anything to learn as much as possible!

**Comment by break69** [comment]
Sorry for my english...
But, maybe step by step
For me the resolution 4k is in last, after first release

**Comment by rootoor225** [comment]
We should define maybe technologies to be applied in order to make everybody know what will in use in the project

**Comment by kelkun89** [comment]
To close this subject, I think that pc, tablet, telephone is sufficient for this project ;)

**Comment by gallarian** [comment]
ok, i close this issue.
