### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Olivier4477** [Nouvelle-Techno-fr/JeBenevole.fr#18]
Bonjour, 

Je propose de stocker les documents directement dans ce projet github, dans un dossier documentation avec une structure de dossier: 
1. wireframe, puis un fichier excel
2. lien, puis un txt avec des liens à voir (exemple tuto sur le PWA, tuto symfony et autre).

L'idée c'est de regrouper les différentes sources interne au projet, les sources d'informations au même endroit.

Cela peut également aider un nouveau à mieux s'intégrer au projet.

**Comment by gallarian** [comment]
Hi, very good idea @Olivier4477 :)

**Comment by gnut06300** [comment]
Lien vers le fichier zoning wireframe maquette
https://1drv.ms/x/s!AqaPcR5Kp4HygekBAQf45z9k_O2xTA?e=AB1aUr
