### ISSUE TITLE
Define Zoning

### ISSUE THREAD

**Issue by NouvelleTechno** [Nouvelle-Techno-fr/JeBenevole.fr#2]
Let's start with main pages zoning.

Pages to define:

- Home page
- List of offers
- List of demands
- Login
- Registration
- User profile
- Admin dashboard

**Comment by Olivier4477** [comment]
beta.grafikart.fr

**Comment by Olivier4477** [comment]
add a logo or a 'mascot'?

**Comment by Olivier4477** [comment]
Une page d'explication du fonctionnement peut-être.

**Comment by Olivier4477** [comment]
Une page type 'annuaire' des associations qui sont référencé sur le site, rangé par ordre alphabétique peut-etre

**Comment by gnut06300** [comment]
Voici le zoning version desktop validé
![image](https://user-images.githubusercontent.com/73892443/107396537-216d9800-6afe-11eb-90d0-d5c1087d37b0.png)

**Comment by gnut06300** [comment]
Voici le zoning version téléphone validé
![image](https://user-images.githubusercontent.com/73892443/107396640-3ea26680-6afe-11eb-8381-53374448f0f5.png)

**Comment by NouvelleTechno** [comment]
@gnut06300 qui les a validés stp ?

**Comment by gnut06300** [comment]
Benoît sur le Discord

**Comment by gallarian** [comment]
Hello
Benoit has never validated that his is on Discord or here or he will have to show me the post.
It was precisely Benoit who asked the question

**Comment by gnut06300** [comment]
Ok, j'ai mal compris alors, désolé

**Comment by gnut06300** [comment]
Vous trouverez ici le zoning pour tablette
https://wireframe.cc/NoixdG

**Comment by gnut06300** [comment]
Vous trouverez ici le zoning pour téléphone mobile 
https://wireframe.cc/sUz1FN

**Comment by gallarian** [comment]
hi, for zoning mobile and tablet, everyone has validated and I also validate
