### ISSUE TITLE
Define template

### ISSUE THREAD

**Issue by gallarian** [Nouvelle-Techno-fr/JeBenevole.fr#20]

**Comment by rootoor225** [comment]
Definitive template or defining template ?

**Comment by rootoor225** [comment]
SInce hours, I tried to get the meaning of the title of this issue in order to help.

**Comment by J7DevWeb** [comment]
Hello, new color test for the home page template. Is this good ? I wait for your feedback. 
Bonjour, un test de couleur pour la page d'accueil. Dites moi si ça vous convient et ce qu'il faut modifier. https://www.figma.com/file/GIfQzN1IbmDX1LtmZ8PawF/JeBenevole---Home-Page---Desktop?node-id=0%3A1

**Comment by gnut06300** [comment]
Bonjour cette page est la page profil et non la homepage.

**Comment by J7DevWeb** [comment]
Exact, merci. J'ai mis à jour mon commentaire précédent et actualisé le fichier excel.

**Comment by gnut06300** [comment]
Template HomePage téléphone :
https://www.figma.com/file/4HLfKXj8IP91LWb4j4I0ep/JeBenevole-Home-Page-Mobile?node-id=1%3A2

**Comment by gnut06300** [comment]
Template list of offers :
https://www.figma.com/file/vstEz30YBHBZlI7xo57oFD/JeBenevole---Offres---Mobile?node-id=1%3A2

**Comment by J7DevWeb** [comment]
New templates for mobile and desktop :
https://www.figma.com/file/GIfQzN1IbmDX1LtmZ8PawF/JeBenevole---Desktop?node-id=0%3A1 
https://www.figma.com/file/ulvNvbpQEilaVTcp9ZILZi/JeBenevole---mobile?node-id=0%3A1 
We stay tuned for your feedback.

**Comment by J7DevWeb** [comment]
New Templates for tablets : https://www.figma.com/file/JwH9y5Fv7Ve7PIaY5PtpVR/JeBenevole---Tablette?node-id=0%3A1

**Comment by J7DevWeb** [comment]
[Compte rendu du mercredi V2.pdf](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/files/6627139/Compte.rendu.du.mercredi.V2.pdf)
_Wednesday meeting report._

**Comment by J7DevWeb** [comment]
[CompteRendu-mercredi-16-06-21.pdf](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/files/6666131/CompteRendu-mercredi-16-06-21.pdf)
 _Wednesday meeting report._

**Comment by Nox5** [comment]
Thursday meeting report
[jBeCR_xx-xx-21.docx](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/files/6697565/jBeCR_xx-xx-21.docx)

**Comment by J7DevWeb** [comment]
All "created By" templates have been update on figma. Link below : 
https://www.figma.com/file/Nt5z7hmMtWrlYpiRTUkSgI/JeBenevole-Desktop?node-id=0%3A1
https://www.figma.com/file/chFZCKM9PMoAWxKJGVwuuz/JeBenevole-Tablette?node-id=0%3A1
https://www.figma.com/file/KJzuc92xvHXG6FrzsVxo3i/JeBenevole-mobile?node-id=0%3A1
