### ISSUE TITLE
Define Wireframe

### ISSUE THREAD

**Issue by NouvelleTechno** [Nouvelle-Techno-fr/JeBenevole.fr#3]
This will be done when zoning (#2) will be completed

**Comment by gnut06300** [comment]
Wireframe pour desktop https://wireframe.cc/3Gglj0

**Comment by gnut06300** [comment]
https://wireframe.cc/SOdsg9 pour la version mobile

**Comment by Nox5** [comment]
Voici le lien du wireframe de la page des offres pour le desktop https://wireframe.cc/9qIB5K

**Comment by Nox5** [comment]
Voilà pour la page des offres le wireframe pour tablette.
https://wireframe.cc/MmhOky

**Comment by Nox5** [comment]
Voilà pour la page des offres le wireframe pour smartphone.
https://wireframe.cc/8Mebav

**Comment by gnut06300** [comment]
Dimension tablette pour le Wireframe : 
728px 900px

**Comment by Nox5** [comment]
Voici la liste des demandes version tablette => https://wireframe.cc/Qmu3Xe

**Comment by Nox5** [comment]
Version mobile de la liste des demandes https://wireframe.cc/21fW85

**Comment by gnut06300** [comment]
Vous trouverez l'ensemble des wireframe et zonning dans ce tableur : 
https://1drv.ms/x/s!AqaPcR5Kp4HygekBAQf45z9k_O2xTA?e=h9GJYM

**Comment by gnut06300** [comment]
J'ai pris en compte toutes les modifications qui avaient été définie lors de la dernière réunion vous pouvez confirmé que tout est conforme à vos attentes.

**Comment by Nox5** [comment]
J'ai jeté un oeil, ça me semble correcte.
