### ISSUE TITLE
Define project tools

### ISSUE THREAD

**Issue by NouvelleTechno** [Nouvelle-Techno-fr/JeBenevole.fr#4]
Project tools used for the project need to be defined : 
- Which language
- Which platform
- Which framework

**Comment by NouvelleTechno** [comment]
Platform chosen : Symfony

Therefore, main language is PHP

**Comment by gnut06300** [comment]
Pour moi le seul framework que je connais est Bootstrap mais ouvert à 100% pour en utiliser un autre, surtout si on peut avoir la collaboration d'un de ces développeurs.

**Comment by kelkun89** [comment]
> Platform chosen : Symfony
> 
> Therefore, main language is PHP

With Vanilla for javascript " Front End "

**Comment by Olivier4477** [comment]
> > Platform chosen : Symfony
> > Therefore, main language is PHP
> 
> With Vanilla for javascript " Front End "

Je ne connais pas, mais pourquoi pas ;) J'aurais cependant préféré React ou Angular...

**Comment by Thomasfds** [comment]
> > > Platform chosen : Symfony
> > > Therefore, main language is PHP
> > 
> > 
> > With Vanilla for javascript " Front End "
> 
> Je ne connais pas, mais pourquoi pas ;) J'aurais cependant préféré React ou Angular...

Javascript vanilla est javascript tous court.

**Comment by kelkun89** [comment]
I never use react so why not after to see according to our needs but for angular "if I do not say stupidity" the power of angular would allow to make the app completely so use it halfway I do not see the interest. Correct me if I'm wrong !!

**Comment by gallarian** [comment]
is this issue ok?

for the backend language its will be php with the symfony framework
for the frontend its will be the Axentix framework and in addition to the SCSS for the compilation of your CSS

I await your validation to close this issue :)

**Comment by kelkun89** [comment]
it's good for me ;)
