### ISSUE TITLE
CSS and language framework reviews

### ISSUE THREAD

**Issue by kelkun89** [Nouvelle-Techno-fr/JeBenevole.fr#6]
Which css framework did you want to use "Bootstrap, Axentix ..." and which language "css, sass or scss"

**Comment by NouvelleTechno** [comment]
Framework suggestions:
- Bootstrap
- Bulma
- TailwindCSS
- Axentix
- Materialize

Regarding CSS, better to use SCSS in my opinion

**Comment by Olivier4477** [comment]
I have no preference. I suggest however a different freamwork from bootstrap
Yes for SCSS

**Comment by Olivier4477** [comment]
I have no preference. I suggest however a different freamwork from bootstrap
Yes for SCSS

**Comment by kelkun89** [comment]
For me I would say Axentix and scss, after seeing the general opinion " A voting system is possible ? "

**Comment by gnut06300** [comment]
Bonjour perso je partirai sur Bootstrap et CSS car se sont les seuls langages que je connais, pour les autres langages je ne peux me prononcer car je ne connais pas mais je suis ici pour apprendre et progresser donc ouvert à tout.

**Comment by Olivier4477** [comment]
> Bonjour perso je partirai sur Bootstrap et CSS car se sont les seuls langages que je connais, pour les autres langages je ne peux me prononcer car je ne connais pas mais je suis ici pour apprendre et progresser donc ouvert à tout.

donc, raison de + pour ne pas utiliser Bootstrap ^^

**Comment by Thomasfds** [comment]
Hi everyone ! 

For me, i think that Bulma is a good framework !

**Comment by kelkun89** [comment]
I think we should take advantage of this project to test new things for the css framework and the css language.
Personally Axentis I just tested the positioning system so I would like to do a complete project with and knowing that one of the Axentis devs would agree to the code review and that we could also discover things to to evolve. Regarding the scss I never tested so I'm up for it ;)

**Comment by Nox5** [comment]
Je suis pour Bootstrap et CSS, mais je ne connais que ceux-là, c'est surement la raison de mon choix comme gnut06300. Mais la remarque d'Olivier4477 n'est pas mauvaise du tout.

**Comment by kelkun89** [comment]
So we go to Axentix so that everything sees it other than bootstrap and the next project we will go to another choice.
LIKE for vote "yes or no"

**Comment by kelkun89** [comment]
Vote system !! go give your opinion with the word discovery in objective

https://www.strawpoll.me/42444094

For the language I think everyone likes scss so we go on it !!!!

**Comment by kelkun89** [comment]
Say ok vote once it's done !! it's no use waiting if everyone has voted

**Comment by Nox5** [comment]
ok

**Comment by Thomasfds** [comment]
The vote is over and Axentis is the framework selectioned.
