### ISSUE TITLE
Clone de git

### ISSUE THREAD

**Issue by gnut06300** [Nouvelle-Techno-fr/JeBenevole.fr#7]
#Bonjour à tous ,
Etant novice sur github et surtout n'ayant jamais travaillé en collaboratif, j'aurais besoin de savoir si dans mon local je dois cloner le rrepo de mon fork https://github.com/gnut06300/JeBenevole.fr,
ou directement votre repo  https://github.com/Nouvelle-Techno-fr/JeBenevole.fr.git.
Merci d'avance pour votre réponse. 
Je viens de remarquer que je n'arrive pas a mettre un label sur mon issue. Désolé

**Comment by Olivier4477** [comment]
Pour moi tu:
1) Va sur le dossier Nouvelle-Techno-fr/JeBenevole.fr et tu clique sur "fork"
2) Du coup, tu as une copie  du projet dans 'your Repositories"
3) tu git pull le projet de ton repositories
4) tu fait tes branch, tes modifs, tes commit
5) tu fait un pull Requests
6) ensuite je ne me souviens plus y a une histoire de branche après, donc à compléter =)

**Comment by gnut06300** [comment]
Merci Olivier j'ai déjà fait les 2 premières  étape ce soir je me lance pour le pull

**Comment by gnut06300** [comment]
J'ai vu avec Gallarian, c'est peut être évident pour vous mais pour moi ça ne l'était pas, donc je vous le partage. Avant de travailler sur le projet il est préférable de faire régulièrement un pull de sa branche main pour la mettre à jour par rapport aux projet source de Nouvelle-techno.
