### ISSUE TITLE
Dépendance and co

### ISSUE THREAD

**Issue by Olivier4477** [Nouvelle-Techno-fr/JeBenevole.fr#8]
Is it possible to install yarn to be able to make yarn watch?

**Comment by gnut06300** [comment]
Re Yarn est l'équivalent de composer ??

**Comment by NouvelleTechno** [comment]
Yarn means you use webpack, there's no decision to use webpack yet

**Comment by kelkun89** [comment]
> Re Yarn est l'équivalent de composer ??

yarn it's like npm, it's dependency manager
