### ISSUE TITLE
Database Debate 

### ISSUE THREAD

**Issue by kelkun89** [Nouvelle-Techno-fr/JeBenevole.fr#9]
<img width="1431" alt="Capture d’écran 2021-01-14 à 14 02 43" src="https://user-images.githubusercontent.com/59282836/104594408-658d8a00-5671-11eb-8caf-fc05e8282d3d.png">

**Comment by kelkun89** [comment]
Some questions about the BDD
User: why not a "boolean" on the "verified - newletter - rgpd" fields.
jb_offres: I do not understand the facebook and twitter fields with a varchar (3)

**Comment by NouvelleTechno** [comment]
Was on/off value (varchar 3) ;-)

**Comment by NouvelleTechno** [comment]
This view is pure sample, please update as required

**Comment by kelkun89** [comment]
okay ! I did not know

**Comment by Olivier4477** [comment]
Is it possible to make a data dictionary, in other words an array with:
Entity: Familleg_benevole (User example)
Code: offerid
Label (the most important): Id of the offer
the type,
Its constraint (not null)

It's a proposal, but it would allow everyone to know what they are talking about, what it corresponds to ...

Up to you ;)

**Comment by Nox5** [comment]
C'est pas une mauvaise idée

**Comment by Olivier4477** [comment]
et si possible le libellé en anglais & français

**Comment by gnut06300** [comment]
Gallarian la vue que tu as mis c'est la vue du concepteur dans PhpMyAdmin et non je MCD non ?

**Comment by gallarian** [comment]
yes, this is the view of the designer of phpmyadmin and yes it isn't the MCD.
I started it in the other document and await your feedback to make it evolve

**Comment by NouvelleTechno** [comment]
Correct, wrong capture in original document

**Comment by gnut06300** [comment]
Moi j'utilise JMerise pour faire le MCD, si tu en as besoin je peux le faire mais ça sera un peu long

**Comment by gallarian** [comment]
@gnut06300 to do with your colleagues, at this level, I don't impose any tool, you have to choose between you :)

**Comment by gnut06300** [comment]
Bien évidemment si le groupe est majoritairement d'accord

**Comment by Olivier4477** [comment]
https://www.strawpoll.me/42475185 à vous de voter, de choisir =)

**Comment by kelkun89** [comment]
I think it is the person who is responsible for the MCD who chooses the software to use. We're not all going to do the same thing!

**Comment by Nox5** [comment]
I agree
